nexus_challenge/user/models.py
# -*- coding: utf-8 -*-
"""User blueprint models."""

# Standard library modules
import datetime as dt

# Third-party modules
from flask_login import UserMixin
from sqlalchemy.ext.hybrid import hybrid_property

# Application specific modules
from nexus_challenge.database import Column, Model, SurrogatePK, db, reference_col, relationship
from nexus_challenge.extensions import bcrypt


class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(SurrogatePK, Model, UserMixin):
    """A user of the app."""

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    hashed_password = Column(db.LargeBinary(128), nullable=True)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    is_active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)
    is_confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)
    created_on = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    password_reset_token = db.Column(db.String, nullable=True)

    @hybrid_property
    def password(self):
        """Get password."""
        return self.hashed_password

    @password.setter
    def password(self, value):
        """Set password."""
        self.hashed_password = bcrypt.generate_password_hash(value)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        """Full user name."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

nexus_challenge/user/forms.py
# -*- coding: utf-8 -*-
"""User blueprint forms."""

# Standard library modules
import re
from urllib.parse import urljoin, urlparse

# Third-party modules
from flask import redirect, request, url_for
from flask_wtf import FlaskForm
from wtforms import HiddenField, PasswordField, StringField
from wtforms.validators import Email, EqualTo, InputRequired, Length

from nexus_challenge.rules import rules

from .models import User


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and ref_url.netloc == test_url.netloc


def get_redirect_target():
    for target in request.args.get('next'), request.referrer:
        if not target:
            continue
        if is_safe_url(target):
            return target


class RedirectForm(FlaskForm):
    next = HiddenField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.next.data:
            self.next.data = get_redirect_target() or ''

    def redirect(self, endpoint='index', **values):
        if is_safe_url(self.next.data):
            return redirect(self.next.data)
        target = get_redirect_target()
        return redirect(target or url_for(endpoint, **values))


class RegisterForm(FlaskForm):
    """User account registration form."""

    username = StringField('Username', validators=[InputRequired(), Length(min=3, max=25)])
    email = StringField('Email', validators=[InputRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password', validators=[InputRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Repeat password',
        validators=[InputRequired(), EqualTo('password', message='Passwords must match')])
    captcha_challenge = HiddenField(validators=[InputRequired()])
    captcha_answer = StringField(description="Enter the word in all lowercase",
                                 validators=[InputRequired(), Length(min=1, max=20)])

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False

        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append('Username already registered')
            return False

        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append('Email already registered')
            return False

        try:
            section, rule, word = self.captcha_challenge.data.split('-', 2)
            rule = int(rule)
            word = int(word)
            if word <= 0:
                raise ValueError
        except (AttributeError, IndexError, TypeError, ValueError):
            self.captcha_answer.errors.append('Invalid captcha challenge')
            return False

        answer = self.captcha_answer.data.strip().lower()
        if not self.verify_captcha(answer, section, rule, word - 1):
            self.captcha_answer.errors.append('Incorrect captcha answer')
            return False

        return True

    def verify_captcha(self, answer, section, rule, word):
        to_space = '(),.:;'
        xlate_table = str.maketrans(to_space, ' ' * len(to_space), '1234567890"\'\n-_')
        try:
            rule = rules[section][rule].strip().lower()
            rule = re.sub(r'\w+://[a-z/.]+', '', rule)
            rule = rule.translate(xlate_table)
            egg = rule.split()[word]
            return answer == egg
        except (IndexError, KeyError, TypeError, ValueError):
            return False


class LoginForm(RedirectForm):
    """Login authentication form."""

    username = StringField('Username', validators=[InputRequired()])
    password = PasswordField('Password', validators=[InputRequired()])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(LoginForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(LoginForm, self).validate()
        if not initial_validation:
            return False

        self.user = User.query.filter_by(username=self.username.data).first()
        if not self.user:
            self.username.errors.append('Unknown username')
            return False

        if not self.user.is_active:
            self.username.errors.append('User account deactivated')
            return False

        if not self.user.check_password(self.password.data):
            self.password.errors.append('Invalid password')
            return False

        if not self.user.is_confirmed:
            self.username.errors.append('Email confirmation for user account not completed')
            return False

        return True


class ForgotForm(FlaskForm):
    """Forgotten password reset request form."""

    email = StringField('Email',
        validators=[InputRequired(), Email(message=None), Length(min=6, max=255)])

    def validate(self):
        """Validate that a user with given email exists."""
        initial_validation = super(ForgotForm, self).validate()
        if not initial_validation:
            return False

        user = User.query.filter_by(email=self.email.data).first()
        if not user:
            self.email.errors.append('This email is not registered')
            return False

        return True


class ChangePasswordForm(FlaskForm):
    """Change password form."""

    password = PasswordField('Password', validators=[InputRequired(), Length(min=6, max=255)])
    confirm = PasswordField('Repeat password',
        validators=[InputRequired(), EqualTo('password', message='Passwords must match')])

nexus_challenge/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""

from . import views  # noqa

nexus_challenge/user/views.py
# -*- coding: utf-8 -*-
"""User blueprint views."""

# Standard library modules
import random
from datetime import datetime

# Third-party modules
from flask import Blueprint, current_app, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

# Application specific modules
from nexus_challenge.extensions import login_manager
from nexus_challenge.rules import rules
from nexus_challenge.utils import in_submission_period, in_voting_period

from .decorators import check_confirmed
from .email import start_send_email_task
from .forms import ChangePasswordForm, ForgotForm, LoginForm, RegisterForm
from .models import User
from .token import confirm_token, generate_confirmation_token


blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@login_manager.user_loader
def load_user(user_id):
    """Load user by ID."""
    return User.get_by_id(int(user_id))


@blueprint.route('/')
@login_required
def members():
    """Landing page for authenticated users."""
    return render_template('users/members.html')


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    """Handle user account registration form."""
    form = RegisterForm(request.form)

    if form.validate_on_submit():
        token = generate_confirmation_token(form.email.data)
        confirm_url = url_for('user.confirm_email', token=token, _external=True, _scheme='https')
        html = render_template('users/activate.html', confirm_url=confirm_url)
        subject = 'Please confirm your email'
        start_send_email_task(form.email.data, subject, html)
        flash('A confirmation email has been sent to {}.'.format(form.email.data), 'success')

        user = User.create(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
            is_active=True,
            is_confirmed=False
        )
        login_user(user)
        return redirect(url_for('user.unconfirmed'))

    section = random.choice('ABCD')
    captcha_info = {
        'section': section,
        'rule': random.randint(1, len(rules[section])),
        'word': random.randint(1, 5)
    }
    captcha_label = (
        "Anti-robot check: <em>which is the {word}. word of rule {section}.{rule} on the "
        '<a href="/rules/" target="_new">rules</a> page?</em>'
    ).format(**captcha_info)
    return render_template(
        'users/register.html',
        form=form,
        captcha="{section}-{rule}-{word}".format(**captcha_info),
        captcha_label=captcha_label,
    )


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """Handle login form."""
    form = LoginForm(request.form)

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(request.form['password']):
            login_user(user)
            flash('You are logged in.', 'success')
            return form.redirect()
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('users/login.html', form=form)

    return render_template('users/login.html', form=form)


@blueprint.route('/logout')
@login_required
def logout():
    """Handle use logout."""
    logout_user()
    flash('You were logged out.', 'success')
    return redirect(url_for('public.home'))


@blueprint.route('/profile', methods=['GET', 'POST'])
@login_required
@check_confirmed
def profile():
    """Handle user account update form."""
    form = ChangePasswordForm(request.form)

    if form.validate_on_submit():
        user = User.query.filter_by(email=current_user.username).first()

        if user:
            user.update(password=form.password.data)
            flash('Password successfully changed.', 'success')
            return redirect(url_for('user.profile'))
        else:
            flash('Password change was unsuccessful.', 'danger')
            return redirect(url_for('user.profile'))

    return render_template('users/profile.html', form=form)


@blueprint.route('/confirm/<token>')
def confirm_email(token):
    """Handle request from confirmation email link."""
    now = datetime.utcnow()

    max_age = current_app.config.get('REG_TOKEN_MAX_AGE', 3600 * 24 * 10)
    email = confirm_token(token, expiration=max_age)

    if email:
        if not current_user.is_anonymous and email != current_user.email:
            flash('Confirmation invalid for current user. Log out and try again', 'danger')
            return redirect(url_for('public.home'))
        else:
            user = User.query.filter_by(email=email).first_or_404()

            if user.is_confirmed:
                flash('Account already confirmed.', 'success')
            else:
                user.update(is_confirmed=True, confirmed_on=now)
                flash('You have confirmed your account. Thanks!', 'success')

            if current_user.is_anonymous:
                login_user(user)
    else:
        flash('The confirmation link is invalid or has expired.', 'danger')

    if in_submission_period(now):
        return redirect(url_for('competition.manage_entry'))
    elif in_voting_period(now):
        return redirect(url_for('competition.vote'))
    else:
        return redirect(url_for('public.home'))


@blueprint.route('/unconfirmed')
@login_required
def unconfirmed():
    """Show page for for unconfirmed user accounts."""
    if current_user.is_confirmed:
        return redirect(url_for('public.home'))

    return render_template('users/unconfirmed.html')


@blueprint.route('/resend')
@login_required
def resend_confirmation():
    """Re-send user account confirmation email."""
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True, _scheme='https')
    html = render_template('users/activate.html', confirm_url=confirm_url)
    subject = 'Please confirm your email'
    start_send_email_task(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('user.unconfirmed'))


@blueprint.route('/forgot', methods=['GET', 'POST'])
def forgot():
    """Handle forgotten password form."""
    form = ForgotForm(request.form)

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        token = generate_confirmation_token(user.email)
        reset_url = url_for('user.forgot_new', token=token, _external=True, _scheme='https')
        html = render_template('users/reset.html', username=user.email, reset_url=reset_url)
        subject = 'Reset your password'
        start_send_email_task(user.email, subject, html)
        user.update(password_reset_token=token)
        flash('A password reset email has been sent via email.', 'success')
        return redirect(url_for('public.home'))

    return render_template('users/forgot.html', form=form)


@blueprint.route('/forgot/new/<token>', methods=['GET', 'POST'])
def forgot_new(token):
    """Handle update forgotten password form."""
    email = confirm_token(token)
    user = User.query.filter_by(email=email).first_or_404()

    if user.password_reset_token is not None:
        form = ChangePasswordForm(request.form)

        if form.validate_on_submit():
            user = User.query.filter_by(email=email).first()

            if user:
                user.update(password=form.password.data, password_reset_token=None)
                login_user(user)
                flash('Password successfully changed.', 'success')
                return redirect(url_for('user.profile'))

            else:
                flash('Password change was unsuccessful.', 'danger')
                return redirect(url_for('user.profile'))
        else:
            flash('You can now change your password.', 'success')
            return render_template('users/forgot_new.html', form=form)
    else:
        flash('Can not reset the password, try again.', 'danger')

    return redirect(url_for('public.home'))

nexus_challenge/templates/users/activate.html
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>The Open Source Music Nexus Challenge</p>

nexus_challenge/templates/users/forgot.html
{% extends "base.html" %}
{% from 'macros.html' import form_field %}

{% block page_title %}Forgot password{% endblock %}

{% block content %}
<h1 class="mt-5">Forgot Your Password?</h1>

<h2>Enter email address you registered with:</h2>
<form class="form-signin" id="forgotPasswordForm" role="form" method="post" action="">
    {{ form.csrf_token }}
    {{ form_field(form.email, False) }}
    <button type="submit">Reset Password!</button>
</form>
<br/>
<ul>
  <li>Back to <a href="{{ url_for('user.login') }}">login</a></li>
  <li>Need to <a href="{{ url_for('user.register') }}">register</a>?</li>
</ul>
{% endblock %}

nexus_challenge/templates/users/forgot_new.html
{% extends "base.html" %}
{% from 'macros.html' import form_field %}

{% block page_title %}Reset password{% endblock %}

{% block content %}
<h1 class="mt-5">Please Reset Your Password:</h1>
<form class="form-signin" id="resetPasswordForm" role="form" method="post" action="">
  {{ form.csrf_token }}
  {{ form_field(form.password, False) }}
  {{ form_field(form.confirm, False) }}
  <button type="submit">Reset Password!</button>
</form>
{% endblock %}

nexus_challenge/templates/users/login.html
{% extends "base.html" %}
{% from 'macros.html' import form_field %}

{% block page_title %}Sign in{% endblock %}

{% block content %}
<h1 class="mt-5">Please sign in:</h1>
<form class="form-signin" id="loginForm" role="form" method="post" action="">
  {{ form.csrf_token }}
  {{ form.next() }}
  {{ form_field(form.username, False) }}
  {{ form_field(form.password, False) }}
  <button type="submit">Sign in!</button>
</form>
<br/>
<ul>
  <li>Need to <a href="{{ url_for('user.register') }}">Register</a>?</li>
  <li><a href="{{ url_for('user.forgot') }}">Forgot</a> your password?</li>
</ul>
{% endblock %}

nexus_challenge/templates/users/members.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1>Welcome {{ current_user.username }}</h1>
        <h3>This is the members-only page.</h3>
    </div>
{% endblock %}

nexus_challenge/templates/users/profile.html
{% extends "base.html" %}
{% from 'macros.html' import form_field %}

{% block page_title %}Profile{% endblock %}

{% block content %}
<h1 class="mt-5">Your Profile</h1>

{% if current_user.is_authenticated %}
  <p>Email: <strong>{{current_user.email}}</strong></p>
{% endif %}

<h2>Change Password:</h2>
<form class="form-reset" role="form" method="post" action="">
  {{ form.csrf_token }}
  {{ form_field(form.password, False) }}
  {{ form_field(form.confirm, False) }}
  <button type="submit">Update Password!</button>
</form>
{% endblock %}

nexus_challenge/templates/users/register.html
{% extends "base.html" %}
{% from 'macros.html' import form_field %}

{% block page_title %}Register{% endblock %}

{% block content %}
<h1 class="mt-5">Create an Account:</h1>
<form class="form-signin" id="registerForm" role="form" method="post" action="">
  {{ form.csrf_token }}
  {{ form.captcha_challenge(value=captcha) }}
  {{ form_field(form.username, False) }}
  {{ form_field(form.email, False) }}
  {{ form_field(form.password, False) }}
  {{ form_field(form.confirm, False) }}
  {{ form_field(form.captcha_answer, captcha_label) }}
  <button type="submit">Register!</button>
</form>
<br/>
<p>Already have an account? <a href="{{ url_for('user.login') }}">Sign in</a>.</p>
{% endblock %}

nexus_challenge/templates/users/reset.html
<p>Hi!</p>

<p>Somobody requested a password reset for the account {{ username }}.</p>

<p>Click on the following link to reset your password:</p>

<p><a href="{{ reset_url }}">{{ reset_url }}</a></p>

<p>If you didn't request it, you can ignore this email.</p>
<br />
<p>The Open Source Music Nexus Challenge</p>

nexus_challenge/templates/users/unconfirmed.html
{% extends "base.html" %}

{% block page_title %}Unconfirmed account{% endblock %}

{% block content %}
<h1 class="mt-5">Welcome, {{ current_user.username }}!</h1>
<br/>
<p class="no-emphasis">You have not confirmed your account yet. Please check your inbox
(and your spam folder) - you should have received an email with a confirmation link.</p>
<p>Didn't get the email? <a href="{{ url_for('user.resend_confirmation') }}">Resend</a>.</p>
{% endblock %}