nexus_challenge/competition/models.py
# -*- coding: utf-8 -*-
"""Competition blueprint models."""

# Standard library modules
import datetime as dt

# Application specific modules
from nexus_challenge.database import Column, Model, SurrogatePK, db, reference_col, relationship


class CompetitionEntry(SurrogatePK, Model):
    """An entry submitted into the competition."""

    __tablename__ = 'competition_entries'
    title = Column(db.String(100), nullable=False)
    artist = Column(db.String(100), nullable=False)
    url = Column(db.String(255), nullable=False)
    description = Column(db.String(1000))
    production_details = Column(db.String(1000))

    is_published = db.Column(db.Boolean, nullable=False, default=False)
    is_approved = db.Column(db.Boolean, nullable=False, default=False)
    created_on = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    last_modified_on = Column(db.DateTime, nullable=False)
    published_on = Column(db.DateTime)

    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='competition_entries')

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<CompetitionEntry({artist} - {title})>'.format(artist=self.artist, title=self.title)


class Vote(SurrogatePK, Model):
    """A vote for an entry submitted into the competition."""

    __tablename__ = 'competition_votes'
    entry_id = reference_col('competition_entries', nullable=True)
    entry = relationship('CompetitionEntry', backref='votes')
    points = Column(db.Integer, nullable=False, default=0)
    created_on = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='votes')

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Vote(user: {user}, entry: "{artist} - {title}", points: {points})>'.format(
            user=self.user.username,
            artist=self.entry.artist,
            title=self.entry.title,
            points=self.points
        )

nexus_challenge/competition/forms.py
# -*- coding: utf-8 -*-
"""Competition blueprint forms."""

# Third-party modules
from flask import current_app
from flask_login import current_user
from flask_pagedown.fields import PageDownField
from flask_wtf import FlaskForm
from internetarchive import get_item
from wtforms import SelectField, StringField
from wtforms.validators import AnyOf, InputRequired, Length

# Application specific modules
from nexus_challenge.utils import canonify_track_url, format_duration

from .models import CompetitionEntry


class SubmitCompetitionEntryForm(FlaskForm):
    """Login authentication form."""

    title = StringField(
        'Title',
        description="The title of your track",
        validators=[InputRequired(), Length(min=2, max=100)])
    artist = StringField(
        'Artist',
        description="The name of the artist",
        validators=[InputRequired(), Length(min=2, max=100)])
    url = StringField(
        'URL',
        description='The URL or ID of the track on Archive.org, '
                    'e.g. "https://archive.org/details/MyTrack" or "MyTrack"',
        validators=[InputRequired(), Length(min=2, max=255)])
    description = PageDownField(
        'Description',
        description="Describe your track here, e.g. "
                    "mood, style, background story, etc. (Markdown allowed).",
        validators=[InputRequired(), Length(min=10, max=1000)])
    production_details = PageDownField(
        'Production Details',
        description="List all software you used to make the track here (Markdown allowed).",
        validators=[InputRequired(), Length(min=10, max=1000)])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super().__init__(*args, **kwargs)

    def add_form_error(self, msg):
        self.errors.setdefault('form', []).append(msg)

    def validate(self):
        """Validate the form."""
        initial_validation = super().validate()
        if not initial_validation:
            return False

        url, track_id = canonify_track_url(self.url.data)

        try:
            item = get_item(track_id, request_kwargs={'timeout': 30})
            metadata = item.item_metadata.get('metadata')
            if not metadata:
                raise ValueError("'%s' not found." % track_id)
        except Exception as exc:
            self.add_form_error("Could not get meta data from Archive.org: %s" % exc)
        else:
            if metadata.get('title', '').strip().lower() != self.title.data.strip().lower():
                self.add_form_error("Title does not match title in Archive.org meta data.")

            if metadata.get('creator', '').strip().lower() != self.artist.data.strip().lower():
                self.add_form_error("Artist does not match creator / author "
                                    "in Archive.org meta data.")

            flac = None
            for file in getattr(item, 'files', []):
                if file.get('format') == 'Flac':
                    flac = file
                    break
            else:
                self.add_form_error("Track not available in FLAC format.")

            if flac:
                try:
                    length = float(flac.get('length', 0))
                except (TypeError, ValueError):
                    length = 0

                min_length = current_app.config.get('MIN_TRACK_LENGTH', 60.0)
                max_length = current_app.config.get('MAX_TRACK_LENGTH', 300.0)

                if length < min_length:
                    self.add_form_error("Track does not have minimum required duration (%s min.)."
                                        % format_duration(min_length))
                elif length > max_length:
                    self.add_form_error("Track exceeds maximum allowed duration (%s min.)." %
                                        format_duration(max_length))
            else:
                self.add_form_error("Missing meta data for FLAC download of track.")

        return not self.errors.get('form')


vote_validators = [InputRequired(), AnyOf([-1], message="You must select an entry.")]


class VotingForm(FlaskForm):
    """Form for voting on competition entries."""

    points_to_fields = {
        5: 'first',
        4: 'second',
        3: 'third',
        2: 'fourth',
        1: 'fifth'
    }
    fields_to_points = {v: k for k, v in points_to_fields.items()}

    first = SelectField('5 points to:', coerce=int, validators=vote_validators)
    second = SelectField('4 points to:', coerce=int, validators=vote_validators)
    third = SelectField('3 points to:', coerce=int, validators=vote_validators)
    fourth = SelectField('2 points to:', coerce=int, validators=vote_validators)
    fifth = SelectField('1 point to:', coerce=int, validators=vote_validators)

    def add_form_error(self, msg):
        self.errors.setdefault('form', []).append(msg)

    def validate(self):
        """Validate the form."""
        initial_validation = super().validate()
        if not initial_validation:
            return False

        votes = {k: v for k, v in self.data.items() if k in self.fields_to_points}

        if len(set(votes.values())) < len(votes):
            self.add_form_error("You must select five different competition entries.")

        user_entry = CompetitionEntry.query.filter_by(user_id=current_user.id).first()
        if user_entry:
            for field, entry_id in votes.items():
                if entry_id == user_entry.id:
                    self.add_form_error("You may not vote for your own competition entry.")

        return not self.errors.get('form')

nexus_challenge/competition/__init__.py
# -*- coding: utf-8 -*-
"""Blueprint for competetion section."""

from . import views  # noqa

nexus_challenge/competition/views.py
# -*- coding: utf-8 -*-
"""Public blueprint views."""

# Standard library modules
import random
from datetime import datetime
from operator import attrgetter, itemgetter

# Third-party modules
from flask import Blueprint, current_app, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

# Application specific modules
from nexus_challenge.user.decorators import check_confirmed, check_is_admin
from nexus_challenge.user.email import start_send_email_task
from nexus_challenge.utils import (archiveorg_player, canonify_track_url, in_submission_period,
                                   in_voting_period, to_bool)

from .forms import SubmitCompetitionEntryForm, VotingForm
from .models import CompetitionEntry, Vote


blueprint = Blueprint('competition', __name__, static_folder='../static')


# utility functions for this module
def get_user_votes(user):
    votes = {}
    for vote in Vote.query.filter(Vote.user_id == user.id, Vote.points > 0):
        key = VotingForm.points_to_fields.get(vote.points)
        if key:
            votes[key] = vote.entry_id
    return votes


# template context processsors
@blueprint.context_processor
def inject_player():
    return dict(
        archiveorg_player=archiveorg_player,
    )


# request handlers
@blueprint.route('/vote/')
def vote():
    now = datetime.utcnow()
    entries = CompetitionEntry.query.filter_by(is_approved=True)
    order = request.args.get('order')
    desc = to_bool(request.args.get('desc'))

    if order in ('artist', 'title', 'published_on'):
        num_entries = entries.count()
        entries = sorted(entries, key=attrgetter(order), reverse=desc)
    else:
        entries = list(entries)
        num_entries = len(entries)
        random.shuffle(entries)

    if current_user.is_authenticated:
        user_votes = Vote.query.filter_by(user_id=current_user.id)
        user_votes = user_votes.order_by(Vote.points.desc()).limit(5)
    else:
        user_votes = None

    return render_template(
        'competition/vote.html',
        desc=desc,
        entries=entries,
        in_submission_period=in_submission_period(now),
        in_voting_period=in_voting_period(now),
        now=now,
        num_entries=num_entries,
        num_votes=Vote.query.group_by(Vote.user_id).count(),
        order=order,
        user_votes=user_votes,
        user_has_voted=user_votes and user_votes.count()
    )


@blueprint.route('/submit_vote', methods=['GET', 'POST'])
@login_required
@check_confirmed
def submit_vote():
    """Vote submission form page."""
    # check whether voting is attempted outside of competition voting period
    now = datetime.utcnow()
    start_date = current_app.config.get('VOTING_PERIOD_START')
    end_date = current_app.config.get('VOTING_PERIOD_END')

    if start_date and now < start_date:
        flash("The voting period of the competition has not begun yet. "
              "No votes can be submitted at this time.", 'danger')
        return redirect(url_for('competition.vote'))
    elif end_date and now >= end_date:
        flash("The voting period of the competition is over. "
              "Votes cannot be submitted anymore.", 'danger')
        return redirect(url_for('competition.vote'))

    entries = CompetitionEntry.query.filter(
        CompetitionEntry.is_approved == True,  # noqa:E712
        CompetitionEntry.user_id != current_user.id
    )
    entries = [(entry.id, '“{}” by {}'.format(entry.title, entry.artist)) for entry in entries]
    entry_ids = [entry[0] for entry in entries]
    entries.sort(key=itemgetter(1))

    current_votes = get_user_votes(current_user)

    if current_votes:
        form = VotingForm(request.form, **current_votes)
        submit_label = "Submit Vote!"
        meta_title = "Update Vote"
    else:
        # Bogus entry for empty first option of selects
        entries.insert(0, (-1, ""))
        form = VotingForm(request.form, **current_votes)
        submit_label = "Submit Vote!"
        meta_title = "Submit Vote"

    form.first.choices = entries
    # set allowed values for AnyOf validator shared by all select fields
    form.first.validators[1].values = entry_ids
    form.second.choices = entries
    form.third.choices = entries
    form.fourth.choices = entries
    form.fifth.choices = entries

    if form.validate_on_submit():
        for points, field in VotingForm.points_to_fields.items():
            vote = Vote.query.filter_by(user_id=current_user.id, points=points).first()
            entry_id = getattr(form, field).data

            if vote and vote.entry_id == entry_id:
                current_app.logger.debug("Not updating unchanged vote: %r", vote)
            elif vote:
                current_app.logger.debug("Updating vote: %r.", vote)
                vote.update(entry_id=entry_id, created_on=now)
                current_app.logger.debug("New entry: %r", vote.entry)
            else:
                vote = Vote.create(user_id=current_user.id, entry_id=entry_id, points=points,
                                   created_on=now)
                current_app.logger.debug("Created new vote: %r", vote)

        if current_votes:
            flash("Your vote was successfully updated. Thank you for voting!", 'success')
        else:
            flash("Your vote was registered successfully. Thank you for voting!", 'success')
        return redirect(url_for('competition.vote'))
    else:
        return render_template(
            'competition/submit_vote.html',
            form=form,
            submit_label=submit_label,
            meta_title=meta_title
        )


@blueprint.route('/list/')
def list_entries():
    if current_user.is_authenticated and current_user.is_admin:
        entries = CompetitionEntry.query.all()
    else:
        entries = CompetitionEntry.query.filter_by(is_approved=True)

    order = request.args.get('order')
    desc = to_bool(request.args.get('desc'))

    if order in ('artist', 'title', 'published_on'):
        if order == 'published_on':
            def key_func(obj):
                return obj.published_on or datetime.min
        else:
            key_func = attrgetter(order)
        entries = sorted(entries, key=key_func, reverse=desc)
    else:
        entries = list(entries)
        random.shuffle(entries)

    return render_template('competition/list.html', entries=entries, order=order, desc=desc)


@blueprint.route('/view/<int:entry>')
def view_entry(entry):
    entry = CompetitionEntry.get_by_id(entry)
    if not entry or not entry.is_approved:
        flash("Competition entry not found.", 'warning')
        return redirect(url_for('public.home'))

    return render_template('competition/view.html', entry=entry)


@blueprint.route('/submit_entry', methods=['GET', 'POST'])
@login_required
@check_confirmed
def submit_entry():
    """Competition entry submission form page."""
    # check whether submission is attempted outside of competition submission period
    now = datetime.utcnow()
    start_date = current_app.config.get('SUBMISSION_PERIOD_START')
    end_date = current_app.config.get('SUBMISSION_PERIOD_END')

    if start_date and now < start_date:
        flash("The competition submission period has not begun yet. "
              "Entries cannot be submitted or updated at this time.", 'danger')
        return redirect(url_for('competition.manage_entry'))
    elif end_date and now >= end_date:
        flash("The competition submission period is over. "
              "Entries cannot be submitted or updated anymore.", 'danger')
        return redirect(url_for('competition.manage_entry'))

    user_entry = CompetitionEntry.query.filter_by(user_id=current_user.id).first()

    if user_entry:
        form = SubmitCompetitionEntryForm(request.form, obj=user_entry)
        submit_label = "Update Draft!"
        meta_title = "Update Competition Entry"
    else:
        form = SubmitCompetitionEntryForm(request.form)
        submit_label = "Create Draft!"
        meta_title = "Submit Competition Entry"

    if form.validate_on_submit():
        url, _ = canonify_track_url(form.url.data)

        if user_entry:
            if user_entry.is_published:
                flash("Your competition entry is already published "
                      "and can't be updated anymore.", 'danger')
            else:
                user_entry.update(
                    title=form.title.data.strip(),
                    artist=form.artist.data.strip(),
                    url=url,
                    description=form.description.data.strip(),
                    production_details=form.production_details.data.strip(),
                    last_modified_on=datetime.utcnow()
                )
                flash("Your competition entry was successfully updated.", 'success')
        else:
            user_entry = CompetitionEntry.create(
                title=form.title.data.strip(),
                artist=form.artist.data.strip(),
                url=url,
                description=form.description.data.strip(),
                production_details=form.production_details.data.strip(),
                last_modified_on=datetime.utcnow(),
                user_id=current_user.id
            )

            try:
                view_url = url_for('competition.approve', entry=user_entry.id,
                                   _external=True, _scheme='https')
                html = render_template('competition/notify_create.html', view_url=view_url,
                    entry=user_entry, user=current_user)
                subject = 'New competition submission by {}'.format(current_user.username)
                start_send_email_task(current_app.config['SITE_ADMIN_EMAIL'], subject, html)
            except Exception:
                current_app.logger.exception("Error sending entry creation notification.")
            else:
                flash("You successfully created a competition entry.", 'success')

nexus_challenge/templates/competition/list.html
{% extends "base.html" %}

{% block page_title %}Competition Entries{% endblock %}

{% block content %}
{% filter markdown %}
# Competition Entries

This page lists all entries, which have been submitted to the competition. The tracks are listed
in random order by default, but you can choose to display the list sorted by title, artist or date
(published) as well.

*Enjoy listening!*
{% endfilter %}

{% if not entries %}
<p>No competition entries published yet.</p>
{% else %}
<div class="track-list">
  <p class="sort-links">
    Sort by:
    <a href="{{ url_for('competition.list_entries', order='title', desc=1 if (order == 'title' and not desc) else 0) }}"
      >Title{% if order == 'title' and not desc %} (desc){% endif %}</a>&nbsp;|&nbsp;
    <a href="{{ url_for('competition.list_entries', order='artist', desc=1 if (order == 'artist' and not desc) else 0) }}"
      >Artist{% if order == 'artist' and not desc %} (desc){% endif %}</a>&nbsp;|&nbsp;
    <a href="{{ url_for('competition.list_entries', order='published_on', desc=1 if (order == 'published_on' and not desc) else 0) }}"
      >Date{% if order == 'published_on' and not desc %} (desc){% endif %}</a>{% if order %}&nbsp;|&nbsp;<a
      href="{{ url_for('competition.list_entries') }}">Random</a>{% endif %}
  </p>

  {% for entry in entries %}
  <div class="track-list-entry{% if not entry.is_published %} unpublished{% endif %}">
    <p class="track-buttons">
      {% if entry.is_published and not entry.is_approved %}
        <a class="btn btn-sm btn-primary"
          href="{{ url_for('competition.approve', entry=entry.id) }}">Review Entry</a><br/>
      {% elif entry.is_published %}
        <a class="btn btn-sm btn-primary"
          href="{{ url_for('competition.view_entry', entry=entry.id) }}">View details</a><br/>
      {% else %}
      <a class="btn btn-sm btn-primary"
        href="{{ url_for('competition.approve', entry=entry.id) }}">Review entry</a><br/>
      {% endif %}
      <a class="btn btn-sm btn-primary" href="{{ entry.url }}" target="_new"
        title="Visit track on archive.org">Download</a>
    </p>

    <p class="track-title">{{ entry.title }}</p>

    <p class="track-artist">by <span class="artist">{{ entry.artist }}</span></p>

    <p class="track-submit-info">
      Submitted by <span class="username">{{ entry.user.username }}</span> on
      {% if entry.is_published %}
      <span class="published">{{ entry.published_on.strftime('%Y-%m-%d %H:%M UTC') }}</span>
      {% if not entry.is_approved %}(not approved){% endif %}
      {% else %}
      <span class="published">{{ entry.created_on.strftime('%Y-%m-%d %H:%M UTC') }}</span>
      (unpublished)
      {% endif %}
    </p>

    <hr/>

    <div class="track-player">
      {{ archiveorg_player(entry.url, width='100%', id="archiveorg-player-%i" % entry.id) | safe }}
    </div>
  </div>
  {% endfor %}
</div>
{% endif %}
{% endblock %}

nexus_challenge/templates/competition/manage.html
{% extends "base.html" %}

{% block content %}
{% if current_user.is_authenticated %}
{% if entry %}
{% if entry.is_published %}
<h1 class="mt-5">Your Competition Entry</h1>
{% else %}
<h1 class="mt-5">Review Competition Entry Draft</h1>
{% endif %}
<div class="track-list-entry">
  <p class="track-buttons">
    <a class="btn btn-sm btn-primary" href="{{ entry.url }}" target="_new"
      title="Visit track on archive.org">Download</a>
  </p>

  <p class="track-title">{{ entry.title }}</p>

  <p class="track-artist">by <span class="artist">{{ entry.artist }}</span></p>

  <p class="track-submit-info">
    Submitted by
    {% if current_user.is_admin %}
    <span class="username"><a href="mailto:{{ entry.user.email }}">{{ entry.user.username }}</a></span>
    {% else %}
    <span class="username">{{ entry.user.username }}</span>
    {% endif %}
    on <span class="track-date">{{ entry.created_on.strftime('%Y-%m-%d %H:%M UTC') }}</span>
    {% if entry.last_modified_on %}, last modified on
    <span class="track-date">{{ entry.last_modified_on.strftime('%Y-%m-%d %H:%M UTC') }}</span>{% endif %}
  </p>

  <hr/>

  <div class="track-player">
    {{ archiveorg_player(entry.url, width='100%') | safe }}
  </div>
</div>
<div class="flask-markdown shadow-sm rounded">
<p><strong>Description:</strong></p>
{{ entry.description | markdown(autolink=True) }}
</div>
<div class="flask-markdown shadow-sm rounded">
<p><strong>Production details:</strong></p>
{{ entry.production_details | markdown(autolink=True) }}
</div>
{% if entry.is_published %}
  {% if entry.is_approved %}
  <p class="alert alert-success">Your entry was published on
    {{ entry.published_on.strftime('%Y-%m-%d %H:%M UTC') }} and has been approved to enter
    the competition.</p>
  {% else %}
  <p class="alert alert-info">Your entry was published on
    {{ entry.published_on.strftime('%Y-%m-%d %H:%M UTC') }} and is waiting for approval.</p>
  {% endif %}
{% else %}
  {% if in_submission_period %}
  <p class="alert alert-warning">Your entry is not published yet and will <strong>not</strong>
    enter the competition until you publish it.</p>
  {% else %}
  <p class="alert alert-danger">Your entry is not published and does <strong>not</strong> enter
    the competition.</p>
  {% endif %}

  {% if in_submission_period and not entry.is_published %}
  <br/>
  <p>
    <a class="btn btn-secondary" href="{{ url_for('competition.submit_entry') }}">Update entry</a>
    &nbsp;
    <a class="btn btn-danger" href="{{ url_for('competition.publish_entry') }}">Publish Entry</a>
  </p>
  {% endif %}
{% endif %}
{% else %}
{% filter markdown %}
# Enter the Competition

Before you create and submit your entry, make sure you check out the [rules](/rules)!

Then, to enter the competition:

* Upload your track to [Archive.org](https://archive.org/upload/).
* Fill out the [submisison form]({{ url_for('competition.submit_entry') }}) and publish your entry
  before the deadline.

Your can submit your entry to the competition from
**{{ submission_start.strftime('%Y-%m-%d %H:%M:%S UTC') }}** until the deadline on
**{{ submission_end.strftime('%Y-%m-%d %H:%M:%S UTC') }}**.

We **strongly** recommend that you already submit your entry as a draft way before the deadline,
so that you don't miss the deadline due to technical difficulties. You can then publish your
prepared draft submission with a single action.
{% endfilter %}

{% endif %}
{% else %}
{% filter markdown %}
# So You Want To Enter the Competition?

To submit your entry into the competition, you must first
[register an account]({{ url_for('user.register') }}) on this site and then come back to this page.

Already have an account? [Sign in]({{ url_for('user.login') }}).

Before you create and submit your entry, make sure you check out the [rules](/rules)!

Then, to enter the competition:

* Upload your track to [Archive.org](https://archive.org/upload/).
* Fill out the [submisison form]({{ url_for('competition.submit_entry') }}) and publish your entry
  before the deadline.

Your can submit your entry to the competition from
**{{ submission_start.strftime('%Y-%m-%d %H:%M:%S UTC') }}** until the deadline on
**{{ submission_end.strftime('%Y-%m-%d %H:%M:%S UTC') }}**.

We **strongly** recommend that you already submit your entry as a draft way before the deadline,
so that you don't miss the deadline due to technical difficulties. You can then publish your
prepared draft submission with a single action.
{% endfilter %}
{% endif %}
{% endblock %}

nexus_challenge/templates/competition/notify_approve.html
{% filter markdown %}
Hello {{ user.username }},

your competition entry has been approved by the organizer on
{{ approved_on.strftime('%Y-%m-%d %H:%M') }}.

**Title:** *{{ entry.title }}*<br/>
**Artist:** *{{ entry.artist }}*<br/>
**URL:** [{{ entry.url }}]({{ entry.url }})

You can review the entry at [{{ view_url }}]({{ view_url }}).


The Open Source Music Nexus Challenge
{% endfilter %}

nexus_challenge/templates/competition/notify_create.html
{% filter markdown %}
Dear Competition Organizer,

a new competition entry has been submitted by user **{{ user.username }}** on
{{ entry.created_on.strftime('%Y-%m-%d %H:%M') }}.

**Title:** *{{ entry.title }}*<br/>
**Artist:** *{{ entry.artist }}*<br/>
**URL:** [{{ entry.url }}]({{ entry.url }})

You can review the entry at [{{ view_url }}]({{ view_url }}).


The Open Source Music Nexus Challenge
{% endfilter %}

nexus_challenge/templates/competition/vote.html
{% extends "base.html" %}

{% block page_title %}Voting{% endblock %}

{% block content %}
<h1>Voting</h1>

{% if in_voting_period %}
  {% if current_user.is_authenticated %}
    {% if user_has_voted %}
    <p>Your vote was already registered. You can update your vote until the end of the voting
    period.</p>
    {% else %}
    <p>To cast your vote in the competition, please use the voting form:</p>
    {% endif %}

    <p style="text-align: center;"><a class="btn btn-primary"
      href="{{ url_for('competition.submit_vote') }}"
      >{% if user_has_voted %}Update {% endif %}Vote!</a></p>
  {% else %}
    {% filter markdown %}
To cast your vote in the competition, you must first
[register an account]({{ url_for('user.register') }}) on this site and then come back to this
page.

Already have an account? [Sign in]({{ url_for('user.login') }}).
    {% endfilter %}
  {% endif %}
{% endif %}

{% if user_has_voted and now >= voting_start %}
   <p>Here is your vote:</p>
    <p>
      {% for vote in user_votes %}
      <strong>{{ vote.points }} points:</strong>
      <a href="{{ url_for('competition.view_entry', entry=vote.entry.id) }}"
        >“{{ vote.entry.title }}”</a> by <em>{{ vote.entry.artist }}</em><br/>
      {% endfor %}
    </p>
{% endif %}
{% filter markdown %}
The voting period runs from **{{ voting_start.strftime('%Y-%m-%d %H:%M:%S UTC') }}** for
**seven days** until **{{ voting_end.strftime('%Y-%m-%d %H:%M:%S UTC') }}**.

{% if now >= voting_start %}
There are **{{ num_entries }} competition entries** and **{{ num_votes }} users have voted** on
them{% if in_voting_period %} so far{% endif %}.
{% endif %}
{% if in_submission_period %}
In the meanwhile, have a listen to the entries submitted so far. And while you're here: have you
considered [entering the competition](/submit/)?
{% endif %}
{% endfilter %}

{% if now >= submission_start %}
{% filter markdown %}

## Competition Entries

The following entries have been submitted into the
competition{% if in_submission_period %}so far{% endif %}.
The tracks are listed in random order by default, but you can choose to display the list sorted by
title, artist or date (published) as well.

*Enjoy listening!*
{% endfilter %}

{% if not entries %}
<p>No competition entries published yet.</p>
{% else %}
<div class="track-list">
  <p class="sort-links">
    Sort by:
    <a href="{{ url_for('competition.list_entries', order='title', desc=1 if (order == 'title' and not desc) else 0) }}"
      >Title{% if order == 'title' and not desc %} (desc){% endif %}</a>&nbsp;|&nbsp;
    <a href="{{ url_for('competition.list_entries', order='artist', desc=1 if (order == 'artist' and not desc) else 0) }}"
      >Artist{% if order == 'artist' and not desc %} (desc){% endif %}</a>&nbsp;|&nbsp;
    <a href="{{ url_for('competition.list_entries', order='published_on', desc=1 if (order == 'published_on' and not desc) else 0) }}"
      >Date{% if order == 'published_on' and not desc %} (desc){% endif %}</a>{% if order %}&nbsp;|&nbsp;<a
      href="{{ url_for('competition.list_entries') }}">Random</a>{% endif %}
  </p>

  {% for entry in entries %}
  <div class="track-list-entry">
    <p class="track-buttons">
      <a class="btn btn-sm btn-primary"
        href="{{ url_for('competition.view_entry', entry=entry.id) }}">View details</a><br/>
      <a class="btn btn-sm btn-primary" href="{{ entry.url }}" target="_new"
        title="Visit track on archive.org">Download</a>
    </p>

    <p class="track-title">{{ entry.title }}</p>

    <p class="track-artist">by <span class="artist">{{ entry.artist }}</span></p>

    <p class="track-submit-info">
      Submitted by <span class="username">{{ entry.user.username }}</span> on
      <span class="published">{{ entry.published_on.strftime('%Y-%m-%d %H:%M UTC') }}</span>
    </p>

    <hr/>

    <div class="track-player">
      {{ archiveorg_player(entry.url, width='100%', id="archiveorg-player-%i" % entry.id) | safe }}
    </div>
  </div>
  {% endfor %}
</div>
{% endif %}
{% endif %}
{% endblock %}