nexus_challenge/user/views.py
# -*- coding: utf-8 -*-
"""User blueprint views."""

# Standard library modules
import random
from datetime import datetime

# Third-party modules
from flask import Blueprint, current_app, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

# Application specific modules
from nexus_challenge.extensions import login_manager
from nexus_challenge.rules import rules
from nexus_challenge.utils import in_submission_period, in_voting_period

from .decorators import check_confirmed
from .email import start_send_email_task
from .forms import ChangePasswordForm, ForgotForm, LoginForm, RegisterForm
from .models import User
from .token import confirm_token, generate_confirmation_token


blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@login_manager.user_loader
def load_user(user_id):
    """Load user by ID."""
    return User.get_by_id(int(user_id))


@blueprint.route('/')
@login_required
def members():
    """Landing page for authenticated users."""
    return render_template('users/members.html')


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    """Handle user account registration form."""
    form = RegisterForm(request.form)

    if form.validate_on_submit():
        token = generate_confirmation_token(form.email.data)
        confirm_url = url_for('user.confirm_email', token=token, _external=True, _scheme='https')
        html = render_template('users/activate.html', confirm_url=confirm_url)
        subject = 'Please confirm your email'
        start_send_email_task(form.email.data, subject, html)
        flash('A confirmation email has been sent to {}.'.format(form.email.data), 'success')

        user = User.create(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
            is_active=True,
            is_confirmed=False
        )
        login_user(user)
        return redirect(url_for('user.unconfirmed'))

    section = random.choice('ABCD')
    captcha_info = {
        'section': section,
        'rule': random.randint(1, len(rules[section])),
        'word': random.randint(1, 5)
    }
    captcha_label = (
        "Anti-robot check: <em>which is the {word}. word of rule {section}.{rule} on the "
        '<a href="/rules/" target="_new">rules</a> page?</em>'
    ).format(**captcha_info)
    return render_template(
        'users/register.html',
        form=form,
        captcha="{section}-{rule}-{word}".format(**captcha_info),
        captcha_label=captcha_label,
    )


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """Handle login form."""
    form = LoginForm(request.form)

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(request.form['password']):
            login_user(user)
            flash('You are logged in.', 'success')
            return form.redirect()
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('users/login.html', form=form)

    return render_template('users/login.html', form=form)


@blueprint.route('/logout')
@login_required
def logout():
    """Handle use logout."""
    logout_user()
    flash('You were logged out.', 'success')
    return redirect(url_for('public.home'))


@blueprint.route('/profile', methods=['GET', 'POST'])
@login_required
@check_confirmed
def profile():
    """Handle user account update form."""
    form = ChangePasswordForm(request.form)

    if form.validate_on_submit():
        user = User.query.filter_by(email=current_user.username).first()

        if user:
            user.update(password=form.password.data)
            flash('Password successfully changed.', 'success')
            return redirect(url_for('user.profile'))
        else:
            flash('Password change was unsuccessful.', 'danger')
            return redirect(url_for('user.profile'))

    return render_template('users/profile.html', form=form)


@blueprint.route('/confirm/<token>')
def confirm_email(token):
    """Handle request from confirmation email link."""
    now = datetime.utcnow()

    max_age = current_app.config.get('REG_TOKEN_MAX_AGE', 3600 * 24 * 10)
    email = confirm_token(token, expiration=max_age)

    if email:
        if not current_user.is_anonymous and email != current_user.email:
            flash('Confirmation invalid for current user. Log out and try again', 'danger')
            return redirect(url_for('public.home'))
        else:
            user = User.query.filter_by(email=email).first_or_404()

            if user.is_confirmed:
                flash('Account already confirmed.', 'success')
            else:
                user.update(is_confirmed=True, confirmed_on=now)
                flash('You have confirmed your account. Thanks!', 'success')

            if current_user.is_anonymous:
                login_user(user)
    else:
        flash('The confirmation link is invalid or has expired.', 'danger')

    if in_submission_period(now):
        return redirect(url_for('competition.manage_entry'))
    elif in_voting_period(now):
        return redirect(url_for('competition.vote'))
    else:
        return redirect(url_for('public.home'))


@blueprint.route('/unconfirmed')
@login_required
def unconfirmed():
    """Show page for for unconfirmed user accounts."""
    if current_user.is_confirmed:
        return redirect(url_for('public.home'))

    return render_template('users/unconfirmed.html')


@blueprint.route('/resend')
@login_required
def resend_confirmation():
    """Re-send user account confirmation email."""
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True, _scheme='https')
    html = render_template('users/activate.html', confirm_url=confirm_url)
    subject = 'Please confirm your email'
    start_send_email_task(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('user.unconfirmed'))


@blueprint.route('/forgot', methods=['GET', 'POST'])
def forgot():
    """Handle forgotten password form."""
    form = ForgotForm(request.form)

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        token = generate_confirmation_token(user.email)
        reset_url = url_for('user.forgot_new', token=token, _external=True, _scheme='https')
        html = render_template('users/reset.html', username=user.email, reset_url=reset_url)
        subject = 'Reset your password'
        start_send_email_task(user.email, subject, html)
        user.update(password_reset_token=token)
        flash('A password reset email has been sent via email.', 'success')
        return redirect(url_for('public.home'))

    return render_template('users/forgot.html', form=form)


@blueprint.route('/forgot/new/<token>', methods=['GET', 'POST'])
def forgot_new(token):
    """Handle update forgotten password form."""
    email = confirm_token(token)
    user = User.query.filter_by(email=email).first_or_404()

    if user.password_reset_token is not None:
        form = ChangePasswordForm(request.form)

        if form.validate_on_submit():
            user = User.query.filter_by(email=email).first()

            if user:
                user.update(password=form.password.data, password_reset_token=None)
                login_user(user)
                flash('Password successfully changed.', 'success')
                return redirect(url_for('user.profile'))

            else:
                flash('Password change was unsuccessful.', 'danger')
                return redirect(url_for('user.profile'))
        else:
            flash('You can now change your password.', 'success')
            return render_template('users/forgot_new.html', form=form)
    else:
        flash('Can not reset the password, try again.', 'danger')

    return redirect(url_for('public.home'))

nexus_challenge/templates/401.html
{% extends "base.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
{% filter markdown %}
# 401

You are not authorized to see this page. Please [log in]({{ url_for('user.login')}}) or
[create a new account]({{ url_for('user.register') }}).
{% endfilter %}
{% endblock %}

nexus_challenge/templates/archiveorgplayer.html
<iframe class="archiveorg-player" id="{{ id }}"
  src="{{ url }}"
  width="{{ width }}" height="{{ height }}" frameborder="0"
  allowfullscreen webkitallowfullscreen="true" mozallowfullscreen="true">
</iframe>
{% if compat_info %}
<p class="alert alert-primary compat_info">
If you do not see the audio player here, please allow JavaScript and Iframe embedding from
archive.org.
</p>
<script>

if (!checkPlayerIframeLoaded) {
    function checkPlayerIframeLoaded(frame_id) {
        var iframe = $(frame_id);
        // Check if loading is complete
        if (!iframe || iframe.css('display') == 'none') {
            $(".compat_info").show();
        }
    }
}

$(document).ready(function () {
    window.setTimeout(function() { checkPlayerIframeLoaded("#{{ id }}"); }, 3000);
})

$('.compat_info').hide();
</script>
{% endif %}

nexus_challenge/templates/base.html
{% from 'macros.html' import javascript_tag, stylesheet_tag %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block page_title %}{{ meta_title }}{% endblock %} | {{ site_title }}</title>

  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- start Bootstrap 4 CSS from CDN -->
  <link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
  <!-- end Bootstrap 4 CSS from CDN -->
  <!-- start Font Awesome CSS from CDN -->
  <link rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
    integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
    crossorigin="anonymous">
  <!-- end Font Awesome CSS from CDN -->

  <style>
    @font-face {
        font-family: "libretto-icons";
        src:url(/assets/fonts/libretto-icons.eot);
        src:url(/assets/fonts/libretto-icons.eot?#iefix) format("embedded-opentype"),
        url(/assets/fonts/libretto-icons.woff) format("woff"),
        url(/assets/fonts/libretto-icons.ttf) format("truetype"),
        url(/assets/fonts/libretto-icons.svg#libretto-icons) format("svg");
        font-weight: normal;
        font-style: normal;
    }
  </style>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans+Mono|Libre+Baskerville|Montserrat|Playfair+Display">
  {{ stylesheet_tag('styles') | safe }}

  {{ javascript_tag('jquery.min') }}
</head>
<body>
{% block body %}
    <!-- Navigation bar -->
    {% block header %}
    <header class="nav-bar">
        <div class="site-branding">
            <h1 class="site-title">
                <a href="{{ url_for('public.home') }}" title="{{ site_title|e }}" rel="home">{{ site_title|e }}</a>
            </h1>
        </div>
        <nav class="site-navigation" role="navigation">
            <div class="menu-toggle">
                <span class="mobile-site-title">{{ site_title|e }}</span>
            </div>
            <ul class="menu">
                {% for url, text in navigation_links %}
                <li><a href="{{ url }}">{{ text|e }}</a></li>
                {% endfor %}
                {% if current_user and current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.logout') }}"
                      title="Signed in as {{ current_user.username|e }}"
                      ><i class="fas fa-sign-out-alt"></i>&nbsp;Log out</a>
                </li>
              {% endif %}
            </ul>
        </nav>
    </header>
    {% endblock %}

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}" role="alert">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
          {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
    {% endif %}
    {% endwith %}

    <div class="site-content" role="main">
      <article class="format-standard libretto-long-form">
        <div class="entry-content">
{% block content %}{% endblock %}
        </div>
      </article>
    </div>

    <!-- Page Footer -->
    <section class="footer-sidebar clear" role="complementary">
        <div class="widget-block">
            <aside class="widget">
                <h2 class="widget-title">{{ site_title|e }}</h2>
                <div class="widget-text">{{ site_description|e }}</div>
            </aside>
        </div>
    </section>

    <!-- Site Attributions -->
    <footer class="site-footer" role="contentinfo">
        <div class="site-info">
            <p>{{ content_footer }}</p>
            <p>Powered by <a href="https://flask.pocoo.org/">Flask</a> using the
              <a href="https://github.com/abrahamvarricatt/libretto-theme-for-nikola"
              >Libretto theme</a>.</p>
        </div>
        <div class="social">
            <ul class="menu">
                {% for link in social_buttons_code %}
                    <li><a href="{{ link }}"></a></li>
                {% endfor %}
            </ul>
        </div>
    </footer>
<!-- end-of-page JavaScript scripts -->
{% block js_bottom %}{% endblock %}
<!-- Flask-PageDown Markdown in-line editor support -->
{{ pagedown.include_pagedown() }}
{% endblock %}
</body>
</html>

nexus_challenge/templates/macros.html
{% macro stylesheet_tag(name, type='text/css') -%}
    <link rel="stylesheet" type="{{ type }}" href="{{ url_for('static', filename='css/{}.css'.format(name)) }}" />
{%- endmacro %}

{% macro javascript_tag(name, type='text/javascript') -%}
    <script type="{{ type }}" src="{{ url_for('static', filename='js/{}.js'.format(name)) }}"></script>
{%- endmacro %}

{% macro form_field(field, label=True) -%}
    <p>
      {% if label is string %}{{ label|safe }}{% elif label %}{{ field.label }}{% endif %}
      {{ field(placeholder=field.description or ('' if label else field.label.text)) }}
      {% if field.errors %}
      <span class="error">
        {% for error in field.errors %}
          {{ error }}
        {% endfor %}
      </span>
      {% endif %}
    </p>
{%- endmacro %}

{% macro select_field(field, label=True) -%}
    <p>
      {% if label %}{{ field.label }}{% endif %}<br/>
      {{ field() }}
      {% if field.errors %}
      <br/>
      <span class="error">
          {% for error in field.errors %}
            {{ error }}
          {% endfor %}
      </span>
      {% endif %}
    </p>
{%- endmacro %}

{# Renders checkbox fields
    Params:
        field - WTForm field (this isn't checked, but you should put only BooleanFields here.
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few aliases: for - for_, class - class_, class__ - class_

    Example usage:
        {{ macros.render_checkbox_field(form.remember_me) }}
#}
{% macro checkbox_field(field) -%}
    <p class="checkbox">
      <label>
        {{ field(type='checkbox', **kwargs) }} {{ field.label }}
      </label>
    </p>
{%- endmacro %}